name: Mirror to Codeberg and GitLab

on:
  push:
    branches: ["main"]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  git-mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.MIRROR_SSH_PRIVATE_KEY }}
          known_hosts: 'placeholder'

      - name: Adding Known Hosts
        run: |
          ssh-keyscan codeberg.org >> ~/.ssh/known_hosts
          ssh-keyscan gitlab.com >> ~/.ssh/known_hosts

      - name: Mirror to Codeberg
        run: |
          git remote add codeberg git@codeberg.org:markelpher/KookieChan.git || true
          git push --force codeberg "refs/remotes/origin/main:refs/heads/main" "refs/tags/*:refs/tags/*"

      - name: Mirror to GitLab
        run: |
          git remote add gitlab git@gitlab.com:markelpher/kookiechan.git || true
          git push --force gitlab "refs/remotes/origin/main:refs/heads/main" "refs/tags/*:refs/tags/*"